<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PrestigeMotors">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="User">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="FirstName" type="xs:string"/>
                            <xs:element name="LastName" type="xs:string"/>
                            <xs:element name="UserID" type="xs:int"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Car">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ID" type="xs:int"/>
                            <xs:element name="Name" type="xs:string"/>
                            <xs:element name="Type" type="xs:string"/>
                            <xs:element name="Description" type="xs:string"/>
                            <xs:element name="LongDescription" type="xs:string"/>
                            <xs:element name="Image" type="xs:string"/>
                            <xs:element name="Pricing">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="RentPerDay">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:decimal">
                                                        <xs:attribute name="currency" type="xs:string"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>